#!/usr/bin/env bash

### This script was written to extract indivduals from seq.fna files generated by split_libaries.py
### Workflow -> set varibles for input file, primer filename, and list of samples in file
### cont. -> grep over file extracting the both the header and line after (sequence) and sending to an
### appropriately named file.
### Written 02/05/2018 by JFS

input=$(ls *.fna)
primer=${input%.fna}
samples=$(egrep -o '>G[0-9][0-9]' *.fna | sort | uniq | sed 's/>//g')

for i in $samples; do
#	echo $primer
#	echo $input
#	echo $i
	egrep $i -A1 --no-group-separator $input > ${i}_${primer}.fasta
done